samples:
    fastq: [simulated_read1.fq, simulated_read2.fq]
    date: "20200101"
    haps: [0, 1]
    ref_haps: [A, B]
    sim_ref_stem: "/research/rv-02/home/eanderson/Simulated_Data_Wenlan/Simulated_Ref/Fasta"
software:
    minimap: "/home/eanderson/minimap2-2.16_x64-linux/minimap2"
    quast: "/research/rv-02/home/qmao/Scripts/python_virtualenv/quast_v5/env/bin/quast.py"
    bin_by_pid: "/home-02/eanderson/Sentieon_Binning_and_Stratification/bin_by_pid.py"
    seqtk: "/home/qmao/Scripts/seqtk-master/seqtk"
    seqkit: "/home/eanderson/bin/seqkit"
    bedtools: "/home/eanderson/bedtools2/bin/bedtools"
    csvtk: "/home/eanderson/bin/csvtk"
    sam_flt: "/home/eanderson/CHM-eval/dip-call/sam-flt.js"
    vcf_pair: "/home/eanderson/CHM-eval/dip-call/vcf-pair.js"
    strat_svs_script: "/research/rv-02/home/eanderson/CGI_de_novo_sim_Pipeline/stratification_test.py"
    htsbox: "/home/eanderson/CHM-eval.kit/htsbox"
    phase_script: "/research/rv-02/home/eanderson/CGI_de_novo_sim_Pipeline/phase_block_n50.py"
    scaffold: "/research/rv-02/home/eanderson/CGI_de_novo_sim_Pipeline/scaffold_contigs.py"
params:
    platform: "bgi-seq"
    seed_lib: "/research/rv-02/home/eanderson/Resources_And_DBs/Sentieon_Seed_Lib/Sentieon_DB-iter0.fa"
    read_group: "@RG\tID:ssb_library1\tLB:SSB\tSM:NA12878"
    sentieon_install: "/opt/sentieon-genomics-cgv0.5-201911"
    sentieon_license: "sentieon-license-server.completegenomics.com:8991"
    range_barcode: 5000
    min_jaccard: 0.02
    min_contig: 10000
    read_len: 100
    human_ref: "/research/rv-02/home/eanderson/Resources_And_DBs/hs37d5.fa"
    strat_bed_dir: "/home/eanderson/Sentieon_Binning_and_Stratification/stratification_regions/"
    strat_tsv: "/home/eanderson/Sentieon_Binning_and_Stratification/ga4gh_all_coordonly_2.tsv"
    sv_truth: "/research/rv-02/home/eanderson/CGI_de_novo_sim_Pipeline/Ref_Haps_to_hs37d5/truth_contigs_phased.vcf.gz"
threads:
    minimap: 16
    assembly: 100
    quast: 40
